name: CI - Tests and Linting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-lint:
    name: Test and Lint (Python ${{ matrix.python-version }})
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run black formatter check
        run: uv run black --check pre_commit_hooks tests

      - name: Run pylint
        run: uv run pylint pre_commit_hooks

      - name: Run pytest with coverage
        run: uv run pytest tests/ --cov=pre_commit_hooks --cov-report=term-missing --cov-report=xml -v
